<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.springframework.boot</groupId>
    <artifactId>spring-boot-starter-parent</artifactId>
    <version>4.0.0</version>
    <relativePath/> <!-- lookup parent from repository -->
  </parent>
  <groupId>com.engcode</groupId>
  <artifactId>bb1c16e9aa27</artifactId>
  <version>0.0.1-SNAPSHOT</version>
  <packaging>war</packaging>
  <name/>
  <description/>
  <url/>
  <licenses>
    <license/>
  </licenses>
  <developers>
    <developer/>
  </developers>
  <scm>
    <connection/>
    <developerConnection/>
    <tag/>
    <url/>
  </scm>
  <properties>
    <java.version>26</java.version>
    <start-class>code.Engineering</start-class>
    <exec.mainClass>code.Engineering</exec.mainClass>
    <org.mapstruct.version>1.6.3</org.mapstruct.version>
    <maven.compiler.release>23</maven.compiler.release>
    <skipTests>true</skipTests>
  </properties>
  <dependencies>

    <!-- Spring Web Start -->

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-web</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-tomcat</artifactId>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-test</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Spring Web End -->



    <!-- Spring Developer Tools Start -->

    <!-- Hot Reload -->
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-devtools</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>

    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok</artifactId>
      <optional>true</optional>
      <scope>provided</scope>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-docker-compose</artifactId>
      <scope>runtime</scope>
      <optional>true</optional>
    </dependency>

    <!-- Spring Developer Tools End -->



    <!-- Spring Template Engines Start -->

    <!-- Spring Template Engines End -->



    <!-- Spring Security Start -->

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-security</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.security</groupId>
      <artifactId>spring-security-test</artifactId>
      <scope>test</scope>
    </dependency>

    <!-- Spring Security End -->



    <!-- Spring SQL Start -->

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-jdbc</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-jpa</artifactId>
    </dependency>

    <!-- Dependency: H2 DB -->
    <dependency>
      <groupId>com.h2database</groupId>
      <artifactId>h2</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- Dependency: Maria DB -->
    <dependency>
      <groupId>org.mariadb.jdbc</groupId>
      <artifactId>mariadb-java-client</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- Dependency: MySQL -->
    <dependency>
      <groupId>com.mysql</groupId>
      <artifactId>mysql-connector-j</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- Dependency: Oracle -->
    <dependency>
      <groupId>com.oracle.database.jdbc</groupId>
      <artifactId>ojdbc11</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- Dependency: PostgresSQL -->
    <dependency>
      <groupId>org.postgresql</groupId>
      <artifactId>postgresql</artifactId>
      <scope>runtime</scope>
    </dependency>

    <!-- Spring SQL End -->



    <!-- Spring NoSQL Start -->

    <!-- Dependency: Data Redis -->

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-data-redis</artifactId>
    </dependency>

    <!-- Spring NoSQL End -->



    <!-- Spring Messaging Start -->

    <!-- Spring Messaging End -->



    <!-- Spring I/O Start -->

    <!-- Spring I/O End -->



    <!-- Spring Ops Start -->

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-actuator</artifactId>
    </dependency>

    <!-- Spring Ops End -->



    <!-- Spring Observability Start -->

    <dependency>
      <groupId>io.micrometer</groupId>
      <artifactId>micrometer-tracing-bridge-brave</artifactId>
    </dependency>

    <dependency>
      <groupId>io.zipkin.reporter2</groupId>
      <artifactId>zipkin-reporter-brave</artifactId>
    </dependency>

    <!-- Spring Observability End -->



    <!-- Spring Testing Start -->
    <!-- Spring Testing End -->



    <!-- Spring Cloud Start -->
    <!-- Spring Cloud End -->



    <!-- Spring Cloud Config Start -->
    <!-- Spring Cloud Config End -->



    <!-- Spring Cloud Discovery Start -->
    <!-- Spring Cloud Discovery End -->



    <!-- Spring Cloud Routing Start -->
    <!-- Spring Cloud Routing End -->



    <!-- Spring Cloud Circuit Breaker Start -->
    <!-- Spring Cloud Circuit Breaker End -->



    <!-- Spring Cloud Messaging Start -->
    <!-- Spring Cloud Messaging End -->



    <!-- Spring VMware Tanzu Application Service Start -->
    <!-- Spring VMware Tanzu Application Service End -->



    <!-- Spring AI Start -->
    <!-- Spring AI End -->



    <!-- Spring Final Start -->
    <!-- Spring Final End -->



    <!-- Other Dependency Start -->

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-logging</artifactId>
    </dependency>

    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter-validation</artifactId>
    </dependency>

    <dependency>
      <groupId>io.github.cdimascio</groupId>
      <artifactId>java-dotenv</artifactId>
      <version>5.2.2</version>
    </dependency>

    <!-- https://mvnrepository.com/artifact/com.auth0/java-jwt -->
    <dependency>
      <groupId>com.auth0</groupId>
      <artifactId>java-jwt</artifactId>
      <version>4.4.0</version>
    </dependency>

    <!-- https://github.com/jwtk/jjwt -->
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-api</artifactId>
      <version>0.12.6</version>
    </dependency>

    <!-- https://github.com/jwtk/jjwt -->
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-impl</artifactId>
      <version>0.12.6</version>
      <scope>runtime</scope>
    </dependency>

    <!-- https://github.com/jwtk/jjwt -->
    <dependency>
      <groupId>io.jsonwebtoken</groupId>
      <artifactId>jjwt-jackson</artifactId>
      <version>0.12.6</version>
      <scope>runtime</scope>
    </dependency>

    <!-- https://springdoc.org/ -->
    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-starter-webmvc-ui</artifactId>
      <version>2.8.5</version>
    </dependency>

    <dependency>
      <groupId>org.springdoc</groupId>
      <artifactId>springdoc-openapi-ui</artifactId>
      <version>1.6.14</version>
    </dependency>

    <dependency>
      <groupId>org.sonarsource.scanner.maven</groupId>
      <artifactId>sonar-maven-plugin</artifactId>
      <version>4.0.0.4121</version>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-api</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.junit.jupiter</groupId>
      <artifactId>junit-jupiter-engine</artifactId>
      <scope>test</scope>
    </dependency>

    <dependency>
      <groupId>org.hibernate.validator</groupId>
      <artifactId>hibernate-validator</artifactId>
    </dependency>

    <!-- https://mapstruct.org/ -->
    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct</artifactId>
      <version>${org.mapstruct.version}</version>
    </dependency>

    <dependency>
      <groupId>org.mapstruct</groupId>
      <artifactId>mapstruct-processor</artifactId>
      <version>${org.mapstruct.version}</version>
      <scope>provided</scope>
    </dependency>

    <!-- Lombok + MapStruct bridge -->
    <dependency>
      <groupId>org.projectlombok</groupId>
      <artifactId>lombok-mapstruct-binding</artifactId>
      <version>0.2.0</version>
      <scope>provided</scope>
    </dependency>

    <!-- Final Dependency End -->

  </dependencies>

  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <configuration>
          <annotationProcessorPaths>
            <!-- Lombok -->
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
            </path>
            <!-- MapStruct -->
            <path>
              <groupId>org.mapstruct</groupId>
              <artifactId>mapstruct-processor</artifactId>
              <version>${org.mapstruct.version}</version>
            </path>
            <!-- Lombok ↔ MapStruct bridge -->
            <path>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok-mapstruct-binding</artifactId>
              <version>0.2.0</version>
            </path>
          </annotationProcessorPaths>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-maven-plugin</artifactId>
        <configuration>
          <!-- Config Memory RAM -->
          <jvmArguments>
            -Xms512m
            -Xmx4g
            -XX:+UseG1GC
            -XX:MaxGCPauseMillis=200
          </jvmArguments>
          <excludes>
            <exclude>
              <groupId>org.projectlombok</groupId>
              <artifactId>lombok</artifactId>
            </exclude>
          </excludes>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.sonarsource.scanner.maven</groupId>
        <artifactId>sonar-maven-plugin</artifactId>
        <version>4.0.0.4121</version>
      </plugin>
    </plugins>
  </build>

  <!-- Definición de perfiles -->
  <profiles>
    <!-- Perfil para desarrollo -->
    <profile>
      <id>dev</id>
      <activation>
        <!-- Este perfil se activa por defecto -->
        <activeByDefault>true</activeByDefault>
      </activation>
      <!-- Start Build -->
      <build>
        <resources>
          <resource>
            <directory>
              src/main/resources
            </directory>
            <filtering>true</filtering>
            <excludes>
              <exclude>application-prod.properties</exclude>
              <exclude>application-stag.properties</exclude>
            </excludes>
          </resource>
        </resources>
      </build>
      <!-- Final Build -->
      <!-- Start Dependencies -->
      <dependencies>
        <!-- Spring Web -->
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
        <!-- Spring Final -->
        <!-- Other Dependency -->
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-logging</artifactId>
        </dependency>
        <!-- Final Dependency -->
        <!-- Other Dependency -->
        <!-- scope: compile o runtime -->
        <!-- <dependency>
          <groupId>jakarta.servlet</groupId>
          <artifactId>jakarta.servlet-api</artifactId>
          <scope>compile</scope>
        </dependency> -->
        <!-- Final Dependency -->
        <!-- Other Dependency -->
        <dependency>
          <groupId>com.mysql</groupId>
          <artifactId>mysql-connector-j</artifactId>
          <scope>compile</scope>
        </dependency>
        <!-- Final Dependency -->
      </dependencies>
      <!-- Final Dependencies -->
      <!-- Start Properties -->
      <properties>
        <build.profile.id>dev</build.profile.id>
        <profileActive>dev</profileActive>
        <skipTests>true</skipTests>
      </properties>
      <!-- Final Properties -->
    </profile>

    <!-- Perfil para pruebas -->
    <profile>
      <id>stag</id>
      <activation>
        <!-- No se activa por defecto -->
        <activeByDefault>false</activeByDefault>
      </activation>
      <!-- Start Build -->
      <build>
        <resources>
          <resource>
            <directory>
              src/main/resources
            </directory>
            <filtering>true</filtering>
            <excludes>
              <exclude>application-dev.properties</exclude>
              <exclude>application-prod.properties</exclude>
            </excludes>
          </resource>
        </resources>
      </build>
      <!-- Final Build -->
      <!-- Start Dependencies -->
      <dependencies>
        <!-- Spring Web -->
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-web</artifactId>
          <exclusions>
            <exclusion>
              <groupId>ch.qos.logback</groupId>
              <artifactId>logback-classic</artifactId>
            </exclusion>
          </exclusions>
        </dependency>
        <!-- Spring Final -->
        <!-- Other Dependency -->
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-logging</artifactId>
          <exclusions>
            <exclusion>
              <groupId>ch.qos.logback</groupId>
              <artifactId>logback-classic</artifactId>
            </exclusion>
          </exclusions>
        </dependency>
        <!-- Final Dependency -->
      </dependencies>
      <!-- Final Dependencies -->
      <!-- Start Properties -->
      <properties>
        <build.profile.id>stag</build.profile.id>
        <profileActive>stag</profileActive>
        <skipTests>true</skipTests>
      </properties>
      <!-- Final Properties -->
    </profile>

    <!-- Perfil para producción -->
    <profile>
      <id>prod</id>
      <activation>
        <!-- No se activa por defecto -->
        <activeByDefault>false</activeByDefault>
      </activation>
      <!-- Start Build -->
      <build>
        <resources>
          <resource>
            <directory>
              src/main/resources
            </directory>
            <filtering>true</filtering>
            <excludes>
              <exclude>application-dev.properties</exclude>
              <exclude>application-stag.properties</exclude>
            </excludes>
          </resource>
        </resources>
      </build>
      <!-- Final Build -->
      <!-- Start Dependencies -->
      <dependencies>
        <!-- Spring Web -->
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-web</artifactId>
          <exclusions>
            <exclusion>
              <groupId>ch.qos.logback</groupId>
              <artifactId>logback-classic</artifactId>
            </exclusion>
          </exclusions>
        </dependency>
        <!-- Spring Final -->
        <!-- Other Dependency -->
        <dependency>
          <groupId>org.springframework.boot</groupId>
          <artifactId>spring-boot-starter-logging</artifactId>
          <exclusions>
            <exclusion>
              <groupId>ch.qos.logback</groupId>
              <artifactId>logback-classic</artifactId>
            </exclusion>
          </exclusions>
        </dependency>
        <!-- Final Dependency -->
      </dependencies>
      <!-- Final Dependencies -->
      <!-- Start Properties -->
      <properties>
        <build.profile.id>prod</build.profile.id>
        <profileActive>prod</profileActive>
        <skipTests>false</skipTests>
      </properties>
      <!-- Final Properties -->
    </profile>
  </profiles>

</project>
