# Core Properties
# spring.application.name=${APP_NAME}
# spring.profiles.active=${APP_ENV}

# Core Properties
spring.application.name=bb1c16e9aa27
# spring.profiles.active=dev
# spring.profiles.active=stag
# spring.profiles.active=prod
spring.profiles.active=@profileActive@
spring.h2.console.enabled=false
# spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration



# Server Properties
server.port=8159



# Documentacion Spring
springdoc.api-docs.path=/v3/api-docs
# springdoc.swagger-ui.supported-submit-methods=method
# Disabling the /v3/api-docs endpoint
springdoc.api-docs.enabled=true
# Swagger NO pasa por Spring Security
springdoc.enable-spring-security=false
springdoc.show-actuator=true
springdoc.swagger-ui.doc-expansion=none
# Disabling the swagger-ui
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=alpha
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.tagsSorter=alpha
springdoc.writer-with-order-by-keys=true
# spring.mvc.pathmatch.matching-strategy=ant-path-matcher





# Docker Compose
spring.docker.compose.enabled=false





# Redis Enable Caching
# spring.cache.type=redis
# Host del servidor
# spring.data.redis.host=127.0.0.1
# Puerto del servidor
# spring.data.redis.port=6379
# spring.data.redis.database=0
# spring.data.redis.timeout=5s





# Enable debug logs.
# spring.zipkin.base-url=http://127.0.0.1:9411
# spring.sleuth.sampler.probability=1.0





# Enable debug logs.
# Habilita los logs de depuración (debug).
debug=false

# Arbitrary properties to add to the info endpoint.
# Propiedades arbitrarias que se añaden al endpoint de información.
#info*=

# Charset to use for console output.
# Charset para la salida en consola.
logging.charset.console=UTF-8

# Charset to use for file output.
# Charset para la salida en archivo.
logging.charset.file=UTF-8

# Location of the logging configuration file. For instance, `classpath:logback.xml` for Logback.
# Ubicación del archivo de configuración de logging.
# logging.config=classpath:logback.xml

# Conversion word used when logging exceptions.
# Palabra de conversión utilizada al registrar excepciones.
logging.exception-conversion-word=%wEx

# Log file name (for instance, `tracing.log`)
# Nombre del archivo de log.
logging.file.name=logs/tracing.log

# Location of the log file. For instance, `/var/log`.
# Ubicación del archivo de log.
logging.file.path=logs

# Log groups to quickly change multiple loggers at the same time. For instance, `logging.group.db=org.hibernate,org.springframework.jdbc`.
# Grupos de logs para cambiar múltiples loggers a la vez.
logging.group.db=org.hibernate,org.springframework.jdbc

# Whether to include the application name in the logs.
# Incluye el nombre de la aplicación en los logs.
logging.include-application-name=true

# Log levels severity mapping. For instance
# Mapeo de niveles de severidad de logs.
# logging.level.org.springframework=DEBUG

# Overriding configuration files used to create a composite configuration
# Archivos de configuración de Log4j2 usados para crear una configuración compuesta.
logging.log4j2.config.override=classpath:log4j2-override.xml

# Whether to clean the archive log files on startup
# Limpia los archivos de log archivados al iniciar.
logging.logback.rollingpolicy.clean-history-on-start=true

# Pattern for rolled-over log file names
# Patrón para los nombres de archivos de log archivados.
# logging.logback.rollingpolicy.file-name-pattern=${LOG_FILE}.%d{yyyy-MM-dd}.%i.gz
logging.logback.rollingpolicy.file-name-pattern=logs/tracing.%d{yyyy-MM-dd}.%i.log.gz

# Maximum log file size
# Tamaño máximo del archivo de log.
logging.logback.rollingpolicy.max-file-size=128MB

# Maximum number of archive log files to keep
# Número máximo de archivos de log archivados a conservar.
logging.logback.rollingpolicy.max-history=7

# Total size of log backups to be kept
# Tamaño total de los archivos de respaldo a conservar.
logging.logback.rollingpolicy.total-size-cap=512MB

# Appender pattern for output to the console
# Patrón del appender para la salida a la consola.
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} - %msg%n

# Appender pattern for log correlation
# Patrón del appender para la correlación de logs.
logging.pattern.correlation=%X{traceId}

# Appender pattern for log date format
# Patrón para el formato de fecha en los logs.
logging.pattern.dateformat=yyyy-MM-dd'T'HH:mm:ss.SSSXXX

# Appender pattern for output to a file
# Patrón del appender para la salida a un archivo.
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n

# Appender pattern for log level
# Patrón del appender para el nivel de log.
logging.pattern.level=%5p

# Register a shutdown hook for the logging system when it is initialized. Disabled automatically when deployed as a war file
# Registra un hook de apagado para el sistema de logging.
logging.register-shutdown-hook=true

# Log level threshold for console output
# Umbral de nivel de log para la salida en consola.
# logging.threshold.console=TRACE

# Log level threshold for file output
# Umbral de nivel de log para la salida en archivo.
# logging.threshold.file=DEBUG

# Log level root
# logging.level.root=DEBUG
